version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    networks:
      - stagledas-net

  stagledas-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL__PASSWORD}
      - MSSQL_PID=${SQL__PID}
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - stagledas-net

  stagledas-rabbitmq:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.mailer
    environment:
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
    depends_on:
      - rabbitmq
      - stagledas-sql
      - stagledas-api
    networks:
      - stagledas-net
    ports:
      - 7111:80

  stagledas-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:staGledas=Server=stagledas-sql,1433;Database=${SQL__DATABASE};User=${SQL__USER};Password=${SQL__PASSWORD};ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5284:5284
    networks:
      - stagledas-net
    links:
      - stagledas-sql
    depends_on:
      - stagledas-sql

networks:
  stagledas-net:
    driver: bridge
