name: stagledas_admin
description: "staGledas Admin - Movie review platform administration"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_side_menu: ^0.5.41
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.1.1
  intl: ^0.20.2
  fl_chart: ^1.1.1
  file_picker: ^10.3.8
  syncfusion_flutter_pdf: ^32.1.22
  path_provider: ^2.1.5
  printing: ^5.14.2
  cross_scroll: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.3
  json_annotation: ^4.9.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/
