name: stagledas_mobile
description: "Sta Gledas? - Movie review and social platform mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  flutter_stripe: ^11.4.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  custom_rating_bar: ^3.0.0
  localstorage: ^4.0.0+1
  cached_network_image: ^3.3.1
  flutter_card_swiper: ^7.0.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10
  url_launcher: ^6.2.5
  signalr_netcore: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/.env
